FROM php:8.4-fpm

LABEL maintainer="Dockerfile du projet NAS-B"

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libzip-dev

# Nettoyer le cache système
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Installer les extensions PHP requises pour Laravel et MySQL
RUN docker-php-ext-install pdo_mysql zip exif pcntl
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd

# Récupérer la dernière version de Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Définir le dossier de travail dans le conteneur
WORKDIR /var/www

# Exposer le port 9000 pour la communication FastCGI avec Nginx
EXPOSE 9000

# Lancer PHP-FPM
CMD ["php-fpm"]